/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.simulacionVehiculo.views;

import autonoma.simulacionVehiculo.exceptions.AcelerarFrenarVehiculoApagadoException;
import autonoma.simulacionVehiculo.exceptions.FrenarVehiculoDetenidoException;
import autonoma.simulacionVehiculo.exceptions.VehiculoAccidentadoException;
import autonoma.simulacionVehiculo.exceptions.VehiculoAceleradoAltamenteException;
import autonoma.simulacionVehiculo.exceptions.VehiculoApagadoException;
import autonoma.simulacionVehiculo.exceptions.VehiculoEncendidoException;
import autonoma.simulacionVehiculo.exceptions.VehiculoPatinandoFrenadoBruscamenteException;
import autonoma.simulacionVehiculo.exceptions.VehiculoPatinandoFrenadoException;
import autonoma.simulacionVehiculo.exceptions.VehiculoRecuperarControlException;
import autonoma.simulacionVehiculo.models.Taller;
import autonoma.simulacionVehiculo.models.Vehiculo;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    Taller taller;
    public VentanaPrincipal(Taller taller) {
        this.taller = taller;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        btnAcelerar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnFrenar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnFondoPantalla = new javax.swing.JPanel();
        pantalla = new javax.swing.JPanel();
        btnEncender = new javax.swing.JPanel();
        txtOn = new javax.swing.JLabel();
        btnApagar = new javax.swing.JPanel();
        txtOf = new javax.swing.JLabel();
        txtVelocidadActual = new javax.swing.JLabel();
        JPTitulo = new javax.swing.JPanel();
        btnMostrarConfiguracionesPosibles = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnVerConfiguracionActual = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        imagenVehiculo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAcelerar.setBackground(new java.awt.Color(204, 204, 204));
        btnAcelerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcelerarMouseClicked(evt);
            }
        });

        jLabel2.setText("Acelerar");

        javax.swing.GroupLayout btnAcelerarLayout = new javax.swing.GroupLayout(btnAcelerar);
        btnAcelerar.setLayout(btnAcelerarLayout);
        btnAcelerarLayout.setHorizontalGroup(
            btnAcelerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAcelerarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        btnAcelerarLayout.setVerticalGroup(
            btnAcelerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAcelerarLayout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        panelPrincipal.add(btnAcelerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 60, 20));

        btnFrenar.setBackground(new java.awt.Color(204, 204, 204));
        btnFrenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFrenarMouseClicked(evt);
            }
        });

        jLabel3.setText("Frenar");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnFrenarLayout = new javax.swing.GroupLayout(btnFrenar);
        btnFrenar.setLayout(btnFrenarLayout);
        btnFrenarLayout.setHorizontalGroup(
            btnFrenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFrenarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        btnFrenarLayout.setVerticalGroup(
            btnFrenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFrenarLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        panelPrincipal.add(btnFrenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, 60, 20));

        btnFondoPantalla.setBackground(new java.awt.Color(0, 0, 0));

        btnEncender.setBackground(new java.awt.Color(102, 153, 255));
        btnEncender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEncenderMouseClicked(evt);
            }
        });

        txtOn.setText("ON");

        javax.swing.GroupLayout btnEncenderLayout = new javax.swing.GroupLayout(btnEncender);
        btnEncender.setLayout(btnEncenderLayout);
        btnEncenderLayout.setHorizontalGroup(
            btnEncenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEncenderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtOn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnEncenderLayout.setVerticalGroup(
            btnEncenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEncenderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtOn, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnApagar.setBackground(new java.awt.Color(255, 153, 153));
        btnApagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnApagarMouseClicked(evt);
            }
        });

        txtOf.setText("OFF");
        txtOf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOfMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnApagarLayout = new javax.swing.GroupLayout(btnApagar);
        btnApagar.setLayout(btnApagarLayout);
        btnApagarLayout.setHorizontalGroup(
            btnApagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnApagarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtOf)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnApagarLayout.setVerticalGroup(
            btnApagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnApagarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtOf, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtVelocidadActual.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtVelocidadActual.setText("Velocidad actual");

        javax.swing.GroupLayout pantallaLayout = new javax.swing.GroupLayout(pantalla);
        pantalla.setLayout(pantallaLayout);
        pantallaLayout.setHorizontalGroup(
            pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnEncender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtVelocidadActual))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pantallaLayout.setVerticalGroup(
            pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pantallaLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(txtVelocidadActual)
                .addGap(18, 18, 18)
                .addComponent(btnEncender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout btnFondoPantallaLayout = new javax.swing.GroupLayout(btnFondoPantalla);
        btnFondoPantalla.setLayout(btnFondoPantallaLayout);
        btnFondoPantallaLayout.setHorizontalGroup(
            btnFondoPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFondoPantallaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnFondoPantallaLayout.setVerticalGroup(
            btnFondoPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantalla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelPrincipal.add(btnFondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 100, 100));

        JPTitulo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout JPTituloLayout = new javax.swing.GroupLayout(JPTitulo);
        JPTitulo.setLayout(JPTituloLayout);
        JPTituloLayout.setHorizontalGroup(
            JPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        JPTituloLayout.setVerticalGroup(
            JPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelPrincipal.add(JPTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 580, -1));

        btnMostrarConfiguracionesPosibles.setBackground(new java.awt.Color(255, 255, 255));
        btnMostrarConfiguracionesPosibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarConfiguracionesPosiblesMouseClicked(evt);
            }
        });

        jLabel6.setText("Mostrar configuraciones");

        javax.swing.GroupLayout btnMostrarConfiguracionesPosiblesLayout = new javax.swing.GroupLayout(btnMostrarConfiguracionesPosibles);
        btnMostrarConfiguracionesPosibles.setLayout(btnMostrarConfiguracionesPosiblesLayout);
        btnMostrarConfiguracionesPosiblesLayout.setHorizontalGroup(
            btnMostrarConfiguracionesPosiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMostrarConfiguracionesPosiblesLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnMostrarConfiguracionesPosiblesLayout.setVerticalGroup(
            btnMostrarConfiguracionesPosiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarConfiguracionesPosiblesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        panelPrincipal.add(btnMostrarConfiguracionesPosibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 160, 30));

        btnVerConfiguracionActual.setBackground(new java.awt.Color(255, 255, 255));
        btnVerConfiguracionActual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerConfiguracionActualMouseClicked(evt);
            }
        });

        jLabel5.setText("ver configuracion actual");

        javax.swing.GroupLayout btnVerConfiguracionActualLayout = new javax.swing.GroupLayout(btnVerConfiguracionActual);
        btnVerConfiguracionActual.setLayout(btnVerConfiguracionActualLayout);
        btnVerConfiguracionActualLayout.setHorizontalGroup(
            btnVerConfiguracionActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVerConfiguracionActualLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnVerConfiguracionActualLayout.setVerticalGroup(
            btnVerConfiguracionActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVerConfiguracionActualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        panelPrincipal.add(btnVerConfiguracionActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, 30));

        imagenVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/simulacionVehiculo/images/interiorVehiculo.png"))); // NOI18N
        imagenVehiculo.setText("jLabel1");
        imagenVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagenVehiculoMouseClicked(evt);
            }
        });
        panelPrincipal.add(imagenVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 581, 664));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncenderMouseClicked
        try{
            String encender = this.taller.getVehiculo().encender();
            JOptionPane.showMessageDialog(null, encender);
        }catch (VehiculoEncendidoException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnEncenderMouseClicked

    private void btnAcelerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcelerarMouseClicked
        try{
            if (this.taller.getVehiculo().isEstado() == false){
                throw new AcelerarFrenarVehiculoApagadoException();
            }
            String aceleracionEntrada = JOptionPane.showInputDialog(null, "Ingrese cuanto desea acelera: ");
            float aceleracion = Float.parseFloat(aceleracionEntrada);
            String mensaje = this.taller.getVehiculo().acelerar(aceleracion);
            JOptionPane.showMessageDialog(null, mensaje);  
            this.txtVelocidadActual.setText(String.valueOf(this.taller.getVehiculo().getVelocidadActual()));
        }catch (AcelerarFrenarVehiculoApagadoException e){
            JOptionPane.showMessageDialog(null, e.getMessage());   
        }catch (VehiculoAceleradoAltamenteException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnAcelerarMouseClicked

    private void txtOfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOfMouseClicked
  
    }//GEN-LAST:event_txtOfMouseClicked

    private void btnFrenarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFrenarMouseClicked
        try{
            if (this.taller.getVehiculo().isEstado() == false){
                throw new AcelerarFrenarVehiculoApagadoException();
            }
            
            if(this.taller.getVehiculo().getVelocidadActual() == 0){
                throw new FrenarVehiculoDetenidoException();
            }
            
            String frenadoEntrada = JOptionPane.showInputDialog(null, "Ingrese cuanto desea frenar: ");
            float frenado = Float.parseFloat(frenadoEntrada);
            String mensaje = this.taller.getVehiculo().frenar(frenado);
            JOptionPane.showMessageDialog(null, mensaje);  
            this.txtVelocidadActual.setText(String.valueOf(this.taller.getVehiculo().getVelocidadActual()));
            
        }catch(AcelerarFrenarVehiculoApagadoException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }catch(FrenarVehiculoDetenidoException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }catch(VehiculoPatinandoFrenadoBruscamenteException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }catch(VehiculoPatinandoFrenadoException e){
            JOptionPane.showMessageDialog(null, e.getMessage()); 
        }catch(VehiculoRecuperarControlException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }       
    }//GEN-LAST:event_btnFrenarMouseClicked

    private void btnApagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApagarMouseClicked
        try{
            String apagar = this.taller.getVehiculo().apagar();
            this.txtVelocidadActual.setText(String.valueOf(this.taller.getVehiculo().getVelocidadActual()));
            JOptionPane.showMessageDialog(null, apagar);
        }catch (VehiculoApagadoException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }catch (VehiculoAccidentadoException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnApagarMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void imagenVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenVehiculoMouseClicked
        
    }//GEN-LAST:event_imagenVehiculoMouseClicked

    private void btnMostrarConfiguracionesPosiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarConfiguracionesPosiblesMouseClicked
        JOptionPane.showMessageDialog(null, this.taller.mostrarPosiblesConfiguraciones() );
    }//GEN-LAST:event_btnMostrarConfiguracionesPosiblesMouseClicked

    private void btnVerConfiguracionActualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerConfiguracionActualMouseClicked
        try {
            JOptionPane.showMessageDialog(null, this.taller.mostrarConfiguracionActual());
        }catch(IOException ex){
            JOptionPane.showConfirmDialog(null, "Error al iniciar el programa, no se puede acceder al archivo configurarVehiculo.txt", "Error", JOptionPane.ERROR);
        }
    }//GEN-LAST:event_btnVerConfiguracionActualMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPTitulo;
    private javax.swing.JPanel btnAcelerar;
    private javax.swing.JPanel btnApagar;
    private javax.swing.JPanel btnEncender;
    private javax.swing.JPanel btnFondoPantalla;
    private javax.swing.JPanel btnFrenar;
    private javax.swing.JPanel btnMostrarConfiguracionesPosibles;
    private javax.swing.JPanel btnVerConfiguracionActual;
    private javax.swing.JLabel imagenVehiculo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel pantalla;
    private javax.swing.JLabel txtOf;
    private javax.swing.JLabel txtOn;
    private javax.swing.JLabel txtVelocidadActual;
    // End of variables declaration//GEN-END:variables
}
